# Generated by Django 3.2.4 on 2021-06-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprdrugdescription',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
